/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {


    public static void main(String[] args) {
        Path path = Paths.get("sample.bmp");
        String theme = "Multiply a Hue";
        String tems = "zoom";
        String color = "color";
        String newPath ="./app/src/main/resources/multiHue.bmp";
        imageReading(path, newPath,color );

    }

    public static void imageReading(Path path, String newPath, String theme){
        try {
            BufferedImage image = ImageIO.read(path.toFile());
            int width = image.getWidth();
            int height = image.getHeight();

            if(theme=="color"){
                for(int row =1; row < width/2;row++){
                    for( int col =1; col< height; col=col+4){

                        Color color = new Color(image.getRGB(row,col));
                        image.setRGB(row, col, 255058190);
                    }
                }}

            if(theme=="zoom"){

                for(int row =1; row < width;row=row+2){
                    for( int col =1; col< height; col=col+2){

                        Color color = new Color(image.getRGB(row,col));
                        image.setRGB(row, col,255058190);
                    }
                }}

            if(theme=="Multiply a Hue"){
                for(int row =1; row < width;row++){
                    for( int col =1; col< height; col++){

                        Color color = new Color(image.getRGB(row,col));
                        int red = color.getRed();
                        image.setRGB(row, col, red);
                    }
                }}
            imageWrite( image,theme );

        }catch(Exception ex){
            System.out.println("Error :" + ex);
        }
    }
    public static void imageWrite(BufferedImage result,String targetName) {

        File output = new File("./app/src/main/resources/"+targetName+".bmp");
        try {
            ImageIO.write(result, "bmp", output);
        } catch (IOException e) {
            System.out.println("ERROR SAVING!");
            System.out.println(e);
        }
    }


}
