/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {


    public static void main(String[] args) {
        Path path = Paths.get("sample.bmp");
        String theme = "Multiply a Hue";
        String newPath ="./app/src/main/resources/multiHue.bmp";
        imageReading(path, newPath,theme );

    }

    public static void imageReading(Path path, String newPath, String theme){
        try {
               BufferedImage image = ImageIO.read(path.toFile());
               int width = image.getWidth();
               int height = image.getHeight();


                 for(int row =1; row < width;row++){
                     for( int col =1; col< height; col++){

                         Color color = new Color(image.getRGB(row,col));

                          int red = color.getRed();
                          int blue = color.getBlue();
                          int green = color.getGreen();
                          int newVals = (red) + (green)+(blue);
                         image.setRGB(row, col, red);
                     }
                 }
            imageWrite( image,theme );
          }catch(Exception ex){
               System.out.println("Error :" + ex);
           }
   }
    public static void imageWrite(BufferedImage result,String targetName) {

        File output = new File("./app/src/main/resources/"+targetName+".bmp");
        try {
            ImageIO.write(result, "bmp", output);
        } catch (IOException e) {
            System.out.println("ERROR SAVING!");
            System.out.println(e);
        }
    }


}
